### ISSUE TITLE
Getting Diff not Found

### ISSUE THREAD

**Issue by Srinivas33431** [Risto-Stevcev/grunt-file-compare#1]
I am getting "Error: Diff not found" always when i run file_compare task, i installed the same using the following command

npm i grunt-file-compare

**Comment by Risto-Stevcev** [comment]
Do you have the `diff` program installed on your pc? I'm guessing you're probably on windows. I'm not too familiar with windows but you can probably install it on power shell. If you want to use a different program then you need to pass the binary name to the `compareBinary` option to choose that instead
